### ISSUE TITLE
Run in background is a RAM + CPU hog

### ISSUE THREAD

**Issue by coaxial** [keensoft/alfresco-simple-ocr#13]
I am playing around with Simple OCR while uploading a large number of documents.

I noticed that if I don't enable the rule to run in background, some of the document uploads time out (408). If I run the task in the background then Alfresco will spawn as many concurrent jobs as there are documents.

This can be a problem when uploading 10+ documents: it consumes huge amounts of RAM by running every job in parallel (regardless of how many CPUs/cores are available). This slows the server down to a grind, and eventually the Linux OOM reaper starts killing processes.

Is there any way to set the plugin so that it only runs a specific number of jobs in parallel? Preferably a number that matches the number of CPUs on the system?

**Comment by douglascrp** [comment]
@Coaxial May you try something like this?
https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/scripts/limitconvert.sh

**Comment by douglascrp** [comment]
@Coaxial The idea is to create a script similar to the one I shared before, and then, inside alfresco-global.properties, use the script with the **ocr.command** parameter.

**Comment by Coaxial** [comment]
Yes, that's what I did. It only fixes part of the problem though, the calls to `pdfsandwich` are throttled, but `gs` and `convert` aren't. I also don't understand whether `taskset` queues the jobs or just assigns them all to specific CPUs and they all run concurrently overloading the designed CPUs.

I'll try setting `img.exe` to the script too, see what happens. I have to wait for the server to stop swapping before I can do anything though hehe

**Comment by angelborroy-ks** [comment]
Have you tried by controlling your `pdfsandwich`process with program options?

[http://www.tobias-elze.de/pdfsandwich/](http://www.tobias-elze.de/pdfsandwich/)

Maybe you can use that `-nthreads` to set a smaller value.

You can also play with Alfresco async thread pool, by setting following properties at `alfresco-global.properties`

```
# Default Async Action Thread Pool
default.async.action.threadPriority=1
default.async.action.corePoolSize=8
default.async.action.maximumPoolSize=20
```

**Comment by twilliamsflcss** [comment]
I had a bit of a different solution to this, you can lower the priority of the at least the Tesseract threads so it won't disable your Alfresco server. I haven't gotten to the Convert or the Unpaper yet though. 

Here you go:

     https://github.com/keensoft/alfresco-simple-ocr/issues/19

**Comment by angelborroy-ks** [comment]
Using OCR installed on an external server will solve this issue.
https://angelborroy.wordpress.com/2017/01/19/alfresco-installing-ocr-as-an-external-service/

**Comment by jacotec** [comment]
Awesome approach, after I've installed Alfresco in the last 3 days as my new DMS I've put 40 docs into a folder today and the whole system immediately stops to react due to the OCR. I've put the OCR into an own VM on my server and all is fine.

Thanks @angelborroy-ks for the great script! However, there are some corrections when you use the parameters as given on the keensoft site.

When using this for pdfsandwich:

```
#ocr.command=/opt/alfresco-community/scripts/pdfsandwich.sh                                                                                
#ocr.output.verbose=true                                                                                                                   
#ocr.output.file.prefix.command=-o                                                                                                         
                                                                                                                                           
#ocr.extra.commands=-verbose -lang eng+deu                                                                                                 
#ocr.server.os=linux  
```

the parameters of the script must look like this:

```
#!/usr/bin/env bash

export LD_LIBRARY_PATH=""

# pdfsandwich hostname
PDFSANDWICH_SERVER="10.0.1.29"

# extract filenames
INPUT=$(basename "$4")
OUTPUT=$(basename "$6")

# SSH parameters
SCP=scp
SSH=ssh

# copy original pdf to pdfsandwich server
$SCP $4 root@$PDFSANDWICH_SERVER:/tmp/$INPUT

# execute pdfsandwich program (requires administrator privileges)
$SSH root@$PDFSANDWICH_SERVER "pdfsandwich $1 $2 $3 /tmp/$INPUT $5 /tmp/$OUTPUT $7"

# copy transformed pdf back to alfresco server
$SCP root@$PDFSANDWICH_SERVER:/tmp/$OUTPUT $6

# remove temporal files
$SSH root@$PDFSANDWICH_SERVER "rm -f /tmp/$INPUT; rm -f /tmp/$OUTPUT"

```

It did also not work for me without the "export..." line in the script.

Unfortunately pdfsandwich did not produce searchable outputs here, neither directly on the Alfresco server nor on the dedicated OCR VM. But ocrmypdf works like a charm! :-)

Here is the setup for ocrmypdf:

```
ocr.command=/opt/alfresco-community/scripts/ocrmypdf.sh                                                                                    
ocr.output.verbose=true                                                                                                                    
ocr.output.file.prefix.command=                                                                                                            
                                                                                                                                           
ocr.extra.commands=--verbose 1 --force-ocr -l eng+deu                                                                                      
ocr.server.os=linux    
```

And finally the shell script:

```
#!/usr/bin/env bash
# set -o xtrace # Uncomment for debugging/troubleshooting

#sudo nice -n 10 /usr/local/bin/ocrmypdf "$@"

export LD_LIBRARY_PATH=""

# pdfsandwich hostname
PDFSANDWICH_SERVER="10.0.1.29"

# extract filenames
INPUT=$(basename "$6")
OUTPUT=$(basename "$7")

# SSH parameters
SCP=scp
SSH=ssh

# copy original pdf to pdfsandwich server
$SCP $6 root@$PDFSANDWICH_SERVER:/tmp/$INPUT

# execute pdfsandwich program (requires administrator privileges)
$SSH root@$PDFSANDWICH_SERVER "ocrmypdf $1 $2 $3 $4 $5 /tmp/$INPUT /tmp/$OUTPUT"

# copy transformed pdf back to alfresco server
$SCP root@$PDFSANDWICH_SERVER:/tmp/$OUTPUT $7

# remove temporal files
$SSH root@$PDFSANDWICH_SERVER "rm -f /tmp/$INPUT; rm -f /tmp/$OUTPUT"

```

Maybe this can help someone ... it took me some time to figure that out ;-)

**Comment by jacotec** [comment]
@angelborroy-ks 

I did some more improvements. When putting dozens of documents into a folder with the OCR rule, the script opens all these tasks in parallel remotely on the OCR server. As ocrmypdf threads seems to generally go to sleep and are not killed after the conversion, this will end in also dozens of sleeping processes on the OCR server.

Second, if a document has multiple pages ocrmypdf will run parallel threads as many CPU cores are available by default. So the CPU load on the OCR server goes always to 100% for a long time in that scenario.

Apart from throwing errors on my monitoring in that case I saw that the kernel ran into a soft watchdog error (CPU core stuck for > 35 seconds) in this scenario, which has killed other processes on the OCR VM. So let's keep it a bit more relaxed:

I've changed my ocrmypdf.sh script which is called on the alfresco server in a way that a new created task creates a local "lock file" with the same name as the source file but with 0 bytes in /tmp on the Alfresco server. Each started script will count the number of files containing "*_source_*" in this directory and will not pass new tasks to the OCR server if a number of tasks (configurable in "maxlimit") is already active. Instead it sleeps for 5 seconds and will try again.

Also I call ocrmypdf with the parameter "--jobs 2" to limit each job to use max. 2 cores instead of unlimited available cores.

This reduces the load and number of remote processes on the OCR server dramatically, also the number of open parallel SSH connections!

The creation of the lockfiles locally instead of counting the number of source files on the remote server itself is necessary as counting the number remotely is too slow and will cause more than maxlimit processes to start.

In addition I call the script "ocr_bootclean.sh" at each system start via rc.local to clear all remaining lockfiles in case the system shuts down or resets with leaving lockfiles in the directory (otherwise the OCR won't work anymore).

I'm really not an expert in bash programming, in case someone wants to improve my scripts you are welcome ;-)

ocrmypdf.sh:

```
#!/usr/bin/env bash
# set -o xtrace # Uncomment for debugging/troubleshooting

export LD_LIBRARY_PATH=""

# pdfsandwich hostname
PDFSANDWICH_SERVER="10.0.1.29"

# Limit number of parallel processed files
maxlimit=2

# extract filenames
INPUT=$(basename "$6")
OUTPUT=$(basename "$7")

# SSH parameters
SCP=scp
SSH=ssh


# wait if there are more than maxnumber of files in process
while true ; do

  # Count number of local Lockfiles
  filecnt=$(find /tmp/ -type f -name '*_source_*' | wc -l)

  # Sleep for 5 seconds when we can't start the process
  if [ $filecnt -lt $maxlimit ]
  then
    break
  fi

  sleep 5s
done

# Create Local "Lockfile"
echo -n > /tmp/$INPUT

# copy original pdf to pdfsandwich server
$SCP $6 root@$PDFSANDWICH_SERVER:/tmp/$INPUT

# execute pdfsandwich program (requires administrator privileges)
$SSH root@$PDFSANDWICH_SERVER "ocrmypdf --jobs 2 $1 $2 $3 $4 $5 /tmp/$INPUT /tmp/$OUTPUT"

# copy transformed pdf back to alfresco server
$SCP root@$PDFSANDWICH_SERVER:/tmp/$OUTPUT $7

# remove temporal files
$SSH root@$PDFSANDWICH_SERVER "rm -f /tmp/$INPUT; rm -f /tmp/$OUTPUT"

# remove Local "Lockfile"
rm -f /tmp/$INPUT
```

ocr_bootclean.sh:

```
#!/usr/bin/env bash

# Clears all remaining Lockfiles in /tmp/
# Needs to run once after machine boot

find /tmp/ -type f -name '*_source_*' -delete
```

**Comment by angelborroy-ks** [comment]
Useful information for everyone. Leave this open for further reference.

Thanks, Marco!
